#!/usr/bin/env python3
"""
Generate input_boolean helpers for each room defined in ha-scripts/rooms.yaml.

Output:
    /config/input_booleans/ha-scripts.yaml
"""

from pathlib import Path
import sys
import yaml
from io import StringIO


HEADER = """# ------------------------------------------------------------------
# Auto-generated by generate_input_booleans.py
# DO NOT EDIT THIS FILE BY HAND — it will be overwritten.
# Edit ha-scripts/rooms.yaml instead and re-run the generator.
# ------------------------------------------------------------------

"""

def main() -> None:
    if len(sys.argv) != 2:
        print("Usage: generate_climates.py /path/to/ha-config", file=sys.stderr)
        sys.exit(1)
    run(Path(sys.argv[1]).expanduser().resolve())

def run(config_root):
    rooms_file = config_root / "ha-scripts" / "rooms.yaml"
    if not rooms_file.exists():
        print(f"rooms.yaml not found at {rooms_file}", file=sys.stderr)
        sys.exit(1)

    input_booleans_dir = config_root / "input_booleans"
    input_booleans_dir.mkdir(parents=True, exist_ok=True)

    output_file = input_booleans_dir / "ha-scripts.yaml"

    rooms = yaml.safe_load(rooms_file.read_text()) or []

    data = {}

    for room in rooms:
            rid = room["id"]
            label = room["label"]   # <-- use label exactly as provided

            data[f"{rid}_heat_request"] = {
                "name": f"{label} Heat Request",
            }

            data[f"{rid}_active"] = {
                "name": f"{label} Active",
            }

    # Global master heat permission switch
    data["heat_permitted"] = {
        "name": "Heat Permitted",
    }

    buf = StringIO()
    yaml.safe_dump(
        data,
        buf,
        sort_keys=True,
        default_flow_style=False,
        allow_unicode=True,
    )

    output_file.write_text(HEADER + buf.getvalue())
    print(f"Wrote {output_file}")


if __name__ == "__main__":
    main()
