#!/usr/bin/env python3
"""
Generate HA template(s) from ha-scripts/rooms.yaml.

Currently generates:
  - binary_sensor.any_room_needs_heat

Output:
  /config/templates/ha-scripts.yaml
"""

from pathlib import Path
import sys
import yaml
from io import StringIO


HEADER = """# ------------------------------------------------------------------
# Auto-generated by generate_templates.py
# DO NOT EDIT THIS FILE BY HAND — it will be overwritten.
# Edit ha-scripts/rooms.yaml instead and re-run the generator.
# ------------------------------------------------------------------

"""

def main() -> None:
    if len(sys.argv) != 2:
        print("Usage: generate_climates.py /path/to/ha-config", file=sys.stderr)
        sys.exit(1)
    run(Path(sys.argv[1]).expanduser().resolve())

def run(config_root):
    rooms_file = config_root / "ha-scripts" / "rooms.yaml"
    if not rooms_file.exists():
        print(f"rooms.yaml not found at {rooms_file}", file=sys.stderr)
        sys.exit(1)

    templates_dir = config_root / "templates"
    templates_dir.mkdir(parents=True, exist_ok=True)

    output_file = templates_dir / "ha-scripts.yaml"

    rooms = yaml.safe_load(rooms_file.read_text()) or []

    parts: list[str] = []
    for room in rooms:
        rid = room["id"]
        parts.append(
            f"(is_state('input_boolean.{rid}_active','on') and "
            f"is_state('input_boolean.{rid}_heat_request','on'))"
        )

    rooms_expr = " or ".join(parts) if parts else "false"
    # Now include master heat_permitted in the sensor itself
    # Final expression:
    # is_state('input_boolean.heat_permitted','on') and (<rooms_expr>)
    expr = (
        "is_state('input_boolean.heat_permitted','on') and "
        f"({rooms_expr})"
    )

    state_expr = f"{{{{ {expr} }}}}"

    data = [
        {
            "binary_sensor": [
                {
                    "name": "Any Room Needs Heat",
                    "unique_id": "any_room_needs_heat",
                    "state": state_expr,
                }
            ]
        }
    ]

    buf = StringIO()
    yaml.safe_dump(
        data,
        buf,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
    )

    output_file.write_text(HEADER + buf.getvalue())
    print(f"Wrote {output_file}")


if __name__ == "__main__":
    main()
