#!/usr/bin/env python3
"""
Generate generic_thermostat climates for each room in ha-scripts/rooms.yaml.

Output:
    /config/climates/ha-scripts.yaml
"""

from pathlib import Path
import sys
import yaml
from io import StringIO


HEADER = """# ------------------------------------------------------------------
# Auto-generated by generate_climates.py
# DO NOT EDIT THIS FILE BY HAND — it will be overwritten.
# Edit ha-scripts/rooms.yaml instead and re-run the generator.
# ------------------------------------------------------------------

"""

def main() -> None:
    if len(sys.argv) != 2:
        print("Usage: generate_climates.py /path/to/ha-config", file=sys.stderr)
        sys.exit(1)
    run(Path(sys.argv[1]).expanduser().resolve())

def run(config_root):
    rooms_file = config_root / "ha-scripts" / "rooms.yaml"
    if not rooms_file.exists():
        print(f"rooms.yaml not found at {rooms_file}", file=sys.stderr)
        sys.exit(1)

    climates_dir = config_root / "climates"
    climates_dir.mkdir(parents=True, exist_ok=True)

    output_file = climates_dir / "ha-scripts.yaml"

    rooms = yaml.safe_load(rooms_file.read_text()) or []

    entries: list[dict] = []

    for room in rooms:
        rid = room["id"]
        label = room["label"]

        temp_sensor = room.get("temp_sensor")
        if not temp_sensor:
            print(
                f"ERROR: room '{rid}' is missing temp_sensor — all rooms must define one.",
                file=sys.stderr,
            )
            sys.exit(1)

        entries.append(
            {
                "platform": "generic_thermostat",
                "name": f"{label} Thermostat",
                "unique_id": f"{rid}_thermostat",
                "heater": f"input_boolean.{rid}_heat_request",
                "target_sensor": temp_sensor,
                # reasonable defaults; tweak later if needed
                "min_temp": 50,
                "max_temp": 80,
                "cold_tolerance": 0.5,
                "hot_tolerance": 0.5,
                "precision": 0.5,
            }
        )

    buf = StringIO()
    yaml.safe_dump(
        entries,
        buf,
        sort_keys=False,
        default_flow_style=False,
        allow_unicode=True,
    )

    output_file.write_text(HEADER + buf.getvalue())
    print(f"Wrote {output_file}")


if __name__ == "__main__":
    main()
